name: appactor_flutter
description: AppActor Flutter SDK — server-authoritative in-app purchase management for iOS and Android.
version: 0.0.11
homepage: https://github.com/appactor/appactor-flutter

environment:
  sdk: ^3.11.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.appactor.appactor_flutter
        pluginClass: AppActorFlutterPlugin
      ios:
        pluginClass: AppActorFlutterPlugin
